# Generated by Django 3.1.3 on 2021-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
